### ISSUE TITLE
Sign Assembly with Strong Name

### ISSUE THREAD

**Issue by swarkentin** [spolnik/Simple.CredentialsManager#1]
The assembly currently uploaded to NuGet is not strong named.

Have you considered signing the assembly with a strong name? I am interested referencing this library in my project, but cannot due to my assemblies being signed.

Thanks!

**Comment by sharwell** [comment]
@spolnik Please let me know if you'd like me to implement this and send a pull request. I've done it many times and the configuration I use now is effortless for everyone involved in the project. :smile:

**Comment by spolnik** [comment]
I'm happy to accept pull request, but as I have no way to build it anymore locally on my machine, I would appreciate help with preparing package for it so you/I can upload it.

All in all, I'm happy to help with signed assembly.
