### ISSUE TITLE
How do i remove windows credentials using this?

### ISSUE THREAD

**Issue by BarisUygun** [spolnik/Simple.CredentialsManager#5]
Hello i need help with deleting a windows credentials with the name "x".

**Comment by BarisUygun** [comment]
I tried using this.

`Simple.CredentialManager.Credential cred;`

how should i use "cred" variable

**Comment by BarisUygun** [comment]
I deleted the generic ones. But i could not delete the windows credentials is it not possible?

**Comment by tts-sdrissen** [comment]
Load() and Delete() an Credential instance to remove it from the Windows Credential Store.
